import Head from "next/head";
import RankingTableComponent from "../../src/components/commons/units/rankingTable/rankingTable.container";

export default function Ranking() {
  return (
    <>
      {/* <Head>    
        <title>SNU Baseball</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/ball.png" />
      </Head> */}
      <div>
        <RankingTableComponent />
      </div>
    </>
  );
}
