// _app.tsx
import { Global, css } from "@emotion/react";
import { RecoilRoot, useSetRecoilState } from "recoil";
import Layout from "../src/components/commons/layout";
import "../styles/globals.css";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { accessTokenState } from "../src/commons/stores";
import {
  registerAccessTokenSetter,
  setAccessToken,
} from "../src/commons/libraries/token";
import API from "../src/commons/apis/api";

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const isResultPage = router.pathname === "/result";
  console.log("대회");

  /* --------- Service Worker 등록 --------- */
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      const onLoad = () =>
        navigator.serviceWorker.register("/sw.js").catch(console.error); // 등록 실패 시 콘솔 확인
      window.addEventListener("load", onLoad);
      return () => window.removeEventListener("load", onLoad);
    }
  }, []);

  /* ---------------------------------------- */

  // // 1) Recoil atom setter 등록
  // const setToken = useSetRecoilState(accessTokenState);
  // useEffect(() => {
  //   registerAccessTokenSetter(setToken);
  // }, [setToken]);

  // // // 2) 초기 로드 시 refresh 호출 → atom에 저장
  // // useEffect(() => {
  // //   API.post("/auth/refresh")
  // //     .then((res) => setAccessToken(res.data.accessToken))
  // //     .catch(() => router.push("/login"));
  // // }, []);

  const globalStyles = css`
    @font-face {
      font-family: "KBO Dia Gothic";
      src: url("/fonts/KBO-Dia-Gothic_medium.woff") format("woff");
      font-weight: normal;
      font-style: normal;
    }
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html,
    body,
    #__next {
      font-family: "KBO-Dia-Gothic_medium";
      background-color: ${isResultPage ? "#f2f2f2" : "#ffffff"};
      margin: 0;
      padding: 0;
      /* height: 100vh; */
      /* height: calc(100% - 140px); */
    }

    /* 2) RootWebArea가 부모 높이(=100%)를 상속하도록 */
    .RootWebArea {
      /* height: 100%; */
      /* 또는 flex 레이아웃이라면 flex: 1; */
    }

    html,
    body,
    #__next,
    .RootWebArea {
      /* height: 100%; */
      margin: 0;
      padding: 0;
    }
  `;

  return (
    <>
      <Head>
        <title>SNU Baseball</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/ball.png" />
      </Head>
      <Global styles={globalStyles} />
      <RecoilRoot>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </RecoilRoot>
    </>
  );
}

export default MyApp;
