import { Global, css } from "@emotion/react";
import { RecoilRoot } from "recoil";
import Layout from "../src/components/commons/layout";
import "../styles/globals.css";
import Head from "next/head";

const globalStyles = css`
  @font-face {
    font-family: "KBO Dia Gothic";
    src: url("/fonts/KBO-Dia-Gothic_medium.woff") format("woff");
    font-weight: normal;
    font-style: normal;
  }

  html,
  body,
  #__next {
    font-family: "KBO Dia Gothic", sans-serif;
  }
`;

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>SNU Baseball</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/ball.png" />
      </Head>
      <Global styles={globalStyles} />
      <RecoilRoot>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </RecoilRoot>
    </>
  );
}

export default MyApp;
