// _app.tsx
import { Global, css } from "@emotion/react";
import { RecoilRoot } from "recoil";
import Layout from "../src/components/commons/layout";
import "../styles/globals.css";
import Head from "next/head";
import { useRouter } from "next/router";

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const isResultPage = router.pathname === "/result";

  const globalStyles = css`
    @font-face {
      font-family: "KBO Dia Gothic";
      src: url("/fonts/KBO-Dia-Gothic_medium.woff") format("woff");
      font-weight: normal;
      font-style: normal;
    }
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html,
    body,
    #__next {
      font-family: "KBO-Dia-Gothic_medium";
      background-color: ${isResultPage ? "#f2f2f2" : "#ffffff"};
      margin: 0;
      padding: 0;
    }
  `;

  return (
    <>
      <Head>
        <title>SNU Baseball</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/ball.png" />
      </Head>
      <Global styles={globalStyles} />
      <RecoilRoot>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </RecoilRoot>
    </>
  );
}

export default MyApp;
