import Head from "next/head";
// import PWAInstallButton from "../src/components/PWAInstallButton";
import MainCalendarPage from "../src/components/commons/units/mainCalendar.container";

export default function Home() {
  return (
    <>
      <Head>
        <title>SNU Baseball</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/ball.png" />
      </Head>
      <div>
        <MainCalendarPage />
        {/* 
        <PWAInstallButton /> */}
      </div>
    </>
  );
}
